name: 'Devici Code Genius Action'
description: 'This GitHub Action runs Devici Code Genius Repository Mode on your code to generate a threat model'
branding:
  icon: 'play'
  color: 'red'
inputs:
  client-id:
    description: 'Client ID for API access from the platform'
    required: false
  client-secret:
    description: 'Client Secret for API access from the platform'
    required: false
  path:
    description: 'Path to the code to analyze'
    required: false
    default: "."
  github-token:
    description: 'GitHub Token'
    required: false
    default: '${{ github.token }}'
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/code_genius'
  args:
    - 'repo'
    - '--print-tree'
    - '${{ inputs.path }}'
  env:
    CG_CLIENT_ID: ${{ inputs.client-id }}
    CG_CLIENT_SECRET: ${{ inputs.client-secret }}
    GITHUB_TOKEN: ${{ inputs.github-token }}
