name: 'Devici Code Genius Action'
description: 'This GitHub Action runs Code Genius on your code to generate a threat model'
inputs:
  verbose-level:
    description: 'Verbosity level (0-2)'
    required: false
    default: "1"
  client-id:
    description: 'Client ID for API access from the platform'
    required: true
  client-secret:
    description: 'Client Secret for API access from the platform'
    required: true
  path:
    description: 'Path to the code to analyze'
    required: true
  github-token:
    description: 'GitHub Token'
    required: true
    default: '${{ github.token }}'
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/code_genius'
  args:
    - 'repo'
    - '--verbose=${{ inputs.verbose-level }}'
    - '--print-tree'
    - '--yes'
    - '${{ inputs.path }}'
  env:
    CG_CLIENT_ID: ${{ inputs.client-id }}
    CG_CLIENT_SECRET: ${{ inputs.client-secret }}
    GITHUB_TOKEN: ${{ inputs.github-token }}
